<a href="https://colab.research.google.com/github/gopalgupta46300-ui/Projects/blob/main/Churn_Modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the specific file you want to load (e.g., 'Churn_Modelling.csv')
file_path = "Churn_Modelling.csv"

# Load the dataset using the updated function
df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "devahuja2808/churn-modeling-dataset",
    file_path
)

df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## DIvide the dataset into independent and dependent features

In [ ]:
X = df.iloc[:, 3:13]
y = df.iloc[:, 13]

In [ ]:
X.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [ ]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

## To add Germany & Spain, Male as category in independent dataset from Gender and Geography

In [ ]:
# categorical feature Engineering
pd.get_dummies(X["Geography"]) # for understanding get_dummies

      France  Germany  Spain
0       True    False  False
1      False    False   True
2       True    False  False
3       True    False  False
4      False    False   True
...      ...      ...    ...
9995    True    False  False
9996    True    False  False
9997    True    False  False
9998   False     True  False
9999    True    False  False

[10000 rows x 3 columns]

In [ ]:
# it drop the first column without rueduce observation
geography = pd.get_dummies(X['Geography'], drop_first=True)

In [ ]:
gender = pd.get_dummies(X['Gender'], drop_first=True)

In [ ]:
# remove the gender and geography
X = X.drop(["Gender", "Geography"], axis=1)
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,42,2,0.00,1,1,1,101348.88
1,608,41,1,83807.86,1,0,1,112542.58
2,502,42,8,159660.80,3,1,0,113931.57
3,699,39,1,0.00,2,0,0,93826.63
4,850,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64
9996,516,35,10,57369.61,1,1,1,101699.77
9997,709,36,7,0.00,1,0,1,42085.58
9998,772,42,3,75075.31,2,1,0,92888.52
9999,792,28,4,130142.79,1,1,0,38190.78

In [ ]:
# add germany, spain, male
X = pd.concat([X, geography, gender], axis=1)
X

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
0,619,42,2,0.00,1,1,1,101348.88,False,False,False
1,608,41,1,83807.86,1,0,1,112542.58,False,True,False
2,502,42,8,159660.80,3,1,0,113931.57,False,False,False
3,699,39,1,0.00,2,0,0,93826.63,False,False,False
4,850,43,2,125510.82,1,1,1,79084.10,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,False,False,False
9998,772,42,3,75075.31,2,1,0,92888.52,True,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,False,False,False

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0 )

In [ ]:
X_train

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
7389,667,34,5,0.00,2,1,0,163830.64,False,True,False
9275,427,42,1,75681.52,1,1,1,57098.00,True,False,True
2995,535,29,2,112367.34,1,1,0,185630.76,False,False,False
5316,654,40,5,105683.63,1,1,0,173617.09,False,True,True
356,850,57,8,126776.30,2,1,1,132298.49,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...
9225,594,32,4,120074.97,2,1,1,162961.79,True,False,False
4859,794,22,4,114440.24,1,1,1,107753.07,False,True,False
3264,738,35,5,161274.05,2,1,0,181429.87,False,False,True
9845,590,38,9,0.00,2,1,1,148750.16,False,True,False
2732,623,48,1,108076.33,1,1,0,118855.26,True,False,False

In [ ]:
X_test

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Germany,Spain,Male
9394,597,35,8,131101.04,1,1,1,192852.67,True,False,False
898,523,40,2,102967.41,1,1,0,128702.10,False,False,False
2398,706,42,8,95386.82,1,1,1,75732.25,False,True,False
5906,788,32,4,112079.58,1,0,0,89368.59,False,False,True
2343,706,38,5,163034.82,2,1,1,135662.17,True,False,True
...,...,...,...,...,...,...,...,...,...,...,...
1037,625,24,1,0.00,2,1,1,180969.55,False,False,False
2899,586,35,7,0.00,2,1,0,70760.69,False,False,False
9549,578,36,1,157267.95,2,1,0,141533.19,False,True,True
2740,650,34,4,142393.11,1,1,1,11276.48,True,False,True
6690,573,30,8,127406.50,1,1,0,192950.60,True,False,True

In [ ]:
from sklearn.preprocessing import StandardScaler # StandardScaler :- based on z-value, and data is mean arounded
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
X_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]], shape=(8000, 11))

In [ ]:
X_test

array([[-0.55204276, -0.36890377,  1.04473698, ...,  1.75486502,
        -0.57369368, -1.09168714],
       [-1.31490297,  0.10961719, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       [ 0.57162971,  0.30102557,  1.04473698, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       ...,
       [-0.74791227, -0.27319958, -1.37744033, ..., -0.5698444 ,
         1.74309049,  0.91601335],
       [-0.00566991, -0.46460796, -0.33936434, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-0.79945688, -0.84742473,  1.04473698, ...,  1.75486502,
        -0.57369368,  0.91601335]], shape=(2000, 11))

In [ ]:
X_train.shape

(8000, 11)

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LeakyReLU, ELU, ReLU, PReLU
from tensorflow.keras.layers import Dropout # drop layer to avoid overfitting, remove the unnessesary nodes

In [ ]:
## lets initialize ANN
classifier = Sequential()
print("classifier object created")

classifier object created

In [ ]:
## input layer
classifier.add(Dense(units=11,activation='relu'))
print("input layer")

input layer

In [ ]:
# first hidden layer
classifier.add(Dense(units=7, activation='relu'))
classifier.add(Dropout (0.2))

In [ ]:
# second hidden layer
classifier.add(Dense(units = 6, activation = 'relu'))
classifier.add(Dropout(0.3))

In [ ]:
# Output layer
classifier.add(Dense(units=1, activation = 'sigmoid'))

In [ ]:
classifier.compile(optimizer = 'adam', loss = "binary_crossentropy", metrics=['accuracy'])
print("compilation is done")

compilation is done

In [ ]:
import tensorflow
opt = tensorflow.keras.optimizers.Adam(learning_rate = 0.01)

In [ ]:
import keras
callback = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    min_delta=0.0001,
    patience=20,
    verbose=1,
    mode="auto",
    baseline=None,
    restore_best_weights=False,
    start_from_epoch=0,
)

In [ ]:
model_history = classifier.fit(X_train, y_train, validation_split = 0.33, batch_size = 20, epochs = 1000, callbacks =[callback])

Epoch 1/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 6s 11ms/step - accuracy: 0.7539 - loss: 0.5708 - val_accuracy: 0.7955 - val_loss: 0.4929
Epoch 2/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.7932 - loss: 0.5076 - val_accuracy: 0.7955 - val_loss: 0.4633
Epoch 3/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7947 - loss: 0.4825 - val_accuracy: 0.7955 - val_loss: 0.4497
Epoch 4/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7959 - loss: 0.4660 - val_accuracy: 0.7955 - val_loss: 0.4402
Epoch 5/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7959 - loss: 0.4562 - val_accuracy: 0.7955 - val_loss: 0.4356
Epoch 6/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7966 - loss: 0.4540 - val_accuracy: 0.7955 - val_loss: 0.4332
Epoch 7/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7998 - loss: 0.4510 - val_accuracy: 0.7944 - val_loss: 0.4310
Epoch 8/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8001 - loss: 0.4541 - val_accuracy: 0.7955 - val_loss: 0.4304
Epoch 9/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8022 - loss: 0.4474 - val_accuracy: 0.7948 - val_loss: 0.4287
Epoch 10/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8041 - loss: 0.4456 - val_accuracy: 0.7989 - val_loss: 0.4279
Epoch 11/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8110 - loss: 0.4387 - val_accuracy: 0.8035 - val_loss: 0.4257
Epoch 12/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8091 - loss: 0.4418 - val_accuracy: 0.8061 - val_loss: 0.4251
Epoch 13/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8115 - loss: 0.4379 - val_accuracy: 0.8171 - val_loss: 0.4228
Epoch 14/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8052 - loss: 0.4400 - val_accuracy: 0.8167 - val_loss: 0.4220
Epoch 15/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8106 - loss: 0.4338 - val_accuracy: 0.8247 - val_loss: 0.4198
Epoch 16/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8169 - loss: 0.4273 - val_accuracy: 0.8277 - val_loss: 0.4175
Epoch 17/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8182 - loss: 0.4275 - val_accuracy: 0.8277 - val_loss: 0.4154
Epoch 18/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8181 - loss: 0.4251 - val_accuracy: 0.8300 - val_loss: 0.4133
Epoch 19/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8197 - loss: 0.4177 - val_accuracy: 0.8349 - val_loss: 0.4102
Epoch 20/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8252 - loss: 0.4180 - val_accuracy: 0.8372 - val_loss: 0.4041
Epoch 21/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8250 - loss: 0.4117 - val_accuracy: 0.8398 - val_loss: 0.3985
Epoch 22/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8347 - loss: 0.4050 - val_accuracy: 0.8413 - val_loss: 0.3925
Epoch 23/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8356 - loss: 0.3925 - val_accuracy: 0.8429 - val_loss: 0.3840
Epoch 24/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8339 - loss: 0.3943 - val_accuracy: 0.8470 - val_loss: 0.3799
Epoch 25/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8365 - loss: 0.3865 - val_accuracy: 0.8493 - val_loss: 0.3762
Epoch 26/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8391 - loss: 0.3827 - val_accuracy: 0.8504 - val_loss: 0.3737
Epoch 27/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8373 - loss: 0.3825 - val_accuracy: 0.8470 - val_loss: 0.3755
Epoch 28/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8362 - loss: 0.3859 - val_accuracy: 0.8497 - val_loss: 0.3726
Epoch 29/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8371 - loss: 0.3777 - val_accuracy: 0.8512 - val_loss: 0.3715
Epoch 30/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8453 - loss: 0.3745 - val_accuracy: 0.8531 - val_loss: 0.3686
Epoch 31/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8345 - loss: 0.3766 - val_accuracy: 0.8523 - val_loss: 0.3697
Epoch 32/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8423 - loss: 0.3755 - val_accuracy: 0.8531 - val_loss: 0.3691
Epoch 33/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8434 - loss: 0.3681 - val_accuracy: 0.8501 - val_loss: 0.3691
Epoch 34/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8377 - loss: 0.3763 - val_accuracy: 0.8538 - val_loss: 0.3684
Epoch 35/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8425 - loss: 0.3725 - val_accuracy: 0.8504 - val_loss: 0.3681
Epoch 36/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8412 - loss: 0.3761 - val_accuracy: 0.8554 - val_loss: 0.3666
Epoch 37/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8401 - loss: 0.3712 - val_accuracy: 0.8550 - val_loss: 0.3680
Epoch 38/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8352 - loss: 0.3754 - val_accuracy: 0.8538 - val_loss: 0.3688
Epoch 39/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8391 - loss: 0.3752 - val_accuracy: 0.8535 - val_loss: 0.3693
Epoch 40/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8399 - loss: 0.3708 - val_accuracy: 0.8531 - val_loss: 0.3682
Epoch 41/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8429 - loss: 0.3675 - val_accuracy: 0.8508 - val_loss: 0.3669
Epoch 42/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8403 - loss: 0.3700 - val_accuracy: 0.8531 - val_loss: 0.3663
Epoch 43/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8440 - loss: 0.3643 - val_accuracy: 0.8531 - val_loss: 0.3667
Epoch 44/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8464 - loss: 0.3680 - val_accuracy: 0.8542 - val_loss: 0.3658
Epoch 45/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8462 - loss: 0.3666 - val_accuracy: 0.8546 - val_loss: 0.3661
Epoch 46/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8373 - loss: 0.3748 - val_accuracy: 0.8554 - val_loss: 0.3654
Epoch 47/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8434 - loss: 0.3632 - val_accuracy: 0.8554 - val_loss: 0.3682
Epoch 48/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8406 - loss: 0.3677 - val_accuracy: 0.8538 - val_loss: 0.3664
Epoch 49/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8447 - loss: 0.3667 - val_accuracy: 0.8527 - val_loss: 0.3669
Epoch 50/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8440 - loss: 0.3681 - val_accuracy: 0.8523 - val_loss: 0.3655
Epoch 51/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8390 - loss: 0.3680 - val_accuracy: 0.8531 - val_loss: 0.3677
Epoch 52/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8399 - loss: 0.3692 - val_accuracy: 0.8542 - val_loss: 0.3659
Epoch 53/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8453 - loss: 0.3652 - val_accuracy: 0.8554 - val_loss: 0.3663
Epoch 54/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8461 - loss: 0.3697 - val_accuracy: 0.8554 - val_loss: 0.3637
Epoch 55/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8421 - loss: 0.3649 - val_accuracy: 0.8538 - val_loss: 0.3658
Epoch 56/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8419 - loss: 0.3646 - val_accuracy: 0.8527 - val_loss: 0.3661
Epoch 57/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8436 - loss: 0.3646 - val_accuracy: 0.8542 - val_loss: 0.3659
Epoch 58/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8399 - loss: 0.3651 - val_accuracy: 0.8550 - val_loss: 0.3645
Epoch 59/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8427 - loss: 0.3690 - val_accuracy: 0.8523 - val_loss: 0.3659
Epoch 60/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8449 - loss: 0.3592 - val_accuracy: 0.8531 - val_loss: 0.3661
Epoch 61/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8444 - loss: 0.3633 - val_accuracy: 0.8523 - val_loss: 0.3655
Epoch 62/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8427 - loss: 0.3627 - val_accuracy: 0.8516 - val_loss: 0.3664
Epoch 63/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8419 - loss: 0.3635 - val_accuracy: 0.8516 - val_loss: 0.3663
Epoch 64/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8421 - loss: 0.3630 - val_accuracy: 0.8531 - val_loss: 0.3648
Epoch 65/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8453 - loss: 0.3634 - val_accuracy: 0.8527 - val_loss: 0.3664
Epoch 66/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8453 - loss: 0.3649 - val_accuracy: 0.8523 - val_loss: 0.3658
Epoch 67/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8449 - loss: 0.3614 - val_accuracy: 0.8504 - val_loss: 0.3665
Epoch 68/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8419 - loss: 0.3615 - val_accuracy: 0.8523 - val_loss: 0.3651
Epoch 69/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8477 - loss: 0.3608 - val_accuracy: 0.8508 - val_loss: 0.3661
Epoch 70/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8436 - loss: 0.3614 - val_accuracy: 0.8501 - val_loss: 0.3674
Epoch 71/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8419 - loss: 0.3595 - val_accuracy: 0.8508 - val_loss: 0.3676
Epoch 72/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8457 - loss: 0.3630 - val_accuracy: 0.8493 - val_loss: 0.3665
Epoch 73/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8438 - loss: 0.3672 - val_accuracy: 0.8512 - val_loss: 0.3669
Epoch 74/1000
268/268 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8442 - loss: 0.3630 - val_accuracy: 0.8504 - val_loss: 0.3653
Epoch 74: early stopping

In [ ]:
model_history.history.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [ ]:
# predict the test values

y_pred = classifier.predict(X_test)
y_pred = (y_pred >= 0.5)

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)
score

0.86

In [ ]:
# to get weights values
classifier.get_weights()

[array([[ 3.82509567e-02,  2.01895088e-01,  8.17754306e-04,
          3.34297031e-01, -8.31225142e-03,  1.02431118e-01,
         -9.76513512e-03,  4.05615419e-02,  2.15170830e-01,
         -2.31406182e-01, -4.36212003e-01],
        [-6.86605752e-01, -6.44113600e-01,  8.29604685e-01,
         -4.35960531e-01,  5.01125932e-01,  1.04998760e-01,
          4.22033183e-02,  2.26977095e-01, -4.67556715e-01,
         -4.97191280e-01, -3.38543236e-01],
        [ 9.79755074e-02,  1.09579496e-01,  3.62792835e-02,
         -1.03394039e-01,  1.19918562e-01,  4.31699693e-01,
         -2.83321720e-02, -2.67010760e-02,  1.08189464e-01,
         -1.23798445e-01,  4.77070212e-02],
        [ 1.11904368e-01,  2.02624097e-01, -3.18013251e-01,
         -8.72256085e-02,  4.60632332e-02, -5.24727046e-01,
          2.60775477e-01, -5.26425838e-01, -3.38388205e-01,
          2.94433594e-01,  1.70040235e-01],
        [ 1.08554758e-01, -1.27656102e-01, -5.51719546e-01,
          2.75111645e-01,  9.15099531e-02,  1.79068714e-01,
          1.13909531e+00,  4.71414566e-01,  3.84235948e-01,
          2.17802122e-01,  3.57841879e-01],
        [-3.96911874e-02,  1.16402678e-01, -1.09470703e-01,
          6.02875531e-01,  1.03463471e-01,  1.20773517e-01,
         -4.82288264e-02,  1.79454498e-02, -5.80823958e-01,
         -4.56973463e-01,  1.40196696e-01],
        [-3.08717519e-01,  1.01687297e-01, -2.20086649e-02,
          8.32606405e-02,  7.30530262e-01,  2.49137223e-01,
          7.70290494e-02,  2.54397839e-01, -2.94632822e-01,
          4.96416479e-01, -1.98436812e-01],
        [ 1.77148417e-01, -7.25729093e-02,  1.19241327e-01,
          4.42632526e-01, -6.53463975e-02, -1.65456653e-01,
         -2.08343789e-02,  1.47931680e-01, -6.83067665e-02,
          7.85998479e-02, -3.23876888e-01],
        [-4.82441001e-02, -3.99124324e-01,  2.27900162e-01,
         -9.42634717e-02, -1.26183674e-01, -2.16460988e-01,
         -2.55895078e-01,  1.91002429e-01, -2.92241275e-01,
         -4.52171415e-02, -7.46488199e-02],
        [-2.34249175e-01, -1.28034037e-02,  1.55465212e-02,
         -2.58431315e-01,  1.77272484e-01,  2.68783391e-01,
          4.26671579e-02,  1.22480698e-01, -1.67774931e-01,
         -1.94599852e-01, -2.56463718e-02],
        [-2.89723873e-01,  9.98342484e-02,  1.15510613e-01,
          2.53586054e-01,  1.54765233e-01,  3.43754962e-02,
          9.77172554e-02,  6.16077334e-02,  4.68321890e-01,
          1.60942331e-01, -5.30813634e-02]], dtype=float32),
 array([-0.14110798,  0.46097368,  0.28743207,  0.29886773, -0.40356103,
         0.04545139, -0.89355344, -0.35705823, -0.15766333,  0.2903124 ,
        -0.06046154], dtype=float32),
 array([[-0.20289664, -0.37763795, -1.2884742 ,  0.3069816 , -0.00310798,
         -0.12384403,  0.25176492],
        [ 0.21587554,  0.02501143,  0.09597161,  0.5848404 , -0.6093476 ,
         -0.4769939 ,  0.36284068],
        [-0.59640616, -0.658569  , -0.1277333 , -0.07201327, -0.6285325 ,
          0.27184626, -0.21968077],
        [ 0.15427096,  0.35994834,  0.02632082,  0.17646554,  0.28169304,
         -0.18214656,  0.13223325],
        [ 0.27650616,  0.30195433,  0.7497719 ,  0.4990484 , -0.5078205 ,
         -0.45849645,  0.55725497],
        [ 0.23874773,  0.25325602, -0.28700918, -0.24104016,  0.53662694,
          0.11617588, -0.11755311],
        [-0.9761692 , -1.0276251 , -0.7441111 , -0.7761512 , -0.8444728 ,
          1.0140443 , -0.8729219 ],
        [ 0.32727683,  0.13965125,  0.464381  ,  0.32368588,  0.23502508,
         -0.3014919 ,  0.26895338],
        [ 0.29500815,  0.23842464,  0.6076854 ,  0.25275588,  0.06830715,
         -0.14854264,  0.3262851 ],
        [ 0.20047984,  0.16735165,  0.0554106 ,  0.12832654,  0.23296121,
         -0.2356202 ,  0.07108513],
        [ 0.16714703,  0.37703788,  0.42516032,  0.17138773,  0.04489168,
         -0.04891326,  0.10645001]], dtype=float32),
 array([ 0.17191035,  0.19226244, -0.29910803, -0.0654984 ,  0.04939663,
        -0.11743408,  0.1985769 ], dtype=float32),
 array([[ 0.56327873,  0.41970447, -0.00821221, -1.3696643 ,  0.23825595,
         -0.04960998],
        [ 0.5741921 ,  0.15561163,  0.75552446, -0.96699095,  0.48224086,
         -0.0450868 ],
        [ 0.97129446,  0.743046  ,  0.844948  , -0.89358747,  0.35429776,
         -0.13159733],
        [ 0.15877406,  0.18947686,  0.68973446, -1.3026756 , -0.19220832,
          0.04838197],
        [ 0.7250267 ,  1.0279958 ,  1.1844884 , -0.5031615 ,  0.4936939 ,
          0.16824736],
        [-0.1270886 , -0.58588445, -0.39668715,  0.7441863 , -0.5774866 ,
         -0.6073103 ],
        [ 0.01723509,  0.26448056, -0.25395468, -1.1734674 ,  0.53136456,
         -0.6251004 ]], dtype=float32),
 array([ 0.01088613,  0.01558606,  0.00797459,  0.476974  , -0.00610359,
        -0.3562737 ], dtype=float32),
 array([[-0.47164863],
        [-0.5084741 ],
        [-0.42849597],
        [ 1.7756993 ],
        [-0.5561456 ],
        [ 0.5002291 ]], dtype=float32),
 array([-0.46770135], dtype=float32)]