<a href="https://colab.research.google.com/github/gopalgupta46300-ui/Projects/blob/main/Movie_Recommendation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.
import kagglehub
tmdb_tmdb_movie_metadata_path = kagglehub.dataset_download('tmdb/tmdb-movie-metadata')
ibtesama_getting_started_with_a_movie_recommendation_system_path = kagglehub.notebook_output_download('ibtesama/getting-started-with-a-movie-recommendation-system')

print('Data source import complete.')

In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/notebooks/ibtesama/getting-started-with-a-movie-recommendation-system/__results__.html
/kaggle/input/notebooks/ibtesama/getting-started-with-a-movie-recommendation-system/__resultx__.html
/kaggle/input/notebooks/ibtesama/getting-started-with-a-movie-recommendation-system/__notebook__.ipynb
/kaggle/input/notebooks/ibtesama/getting-started-with-a-movie-recommendation-system/__output__.json
/kaggle/input/notebooks/ibtesama/getting-started-with-a-movie-recommendation-system/custom.css
/kaggle/input/notebooks/ibtesama/getting-started-with-a-movie-recommendation-system/__results___files/__results___27_1.png
/kaggle/input/datasets/organizations/tmdb/tmdb-movie-metadata/tmdb_5000_movies.csv
/kaggle/input/datasets/organizations/tmdb/tmdb-movie-metadata/tmdb_5000_credits.csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/kaggle/input/datasets/organizations/tmdb/tmdb-movie-metadata/tmdb_5000_movies.csv')
df.head(5)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [ ]:
df.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [ ]:
df['tags'] = df['overview'] + df['genres']
df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,tags
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,"In the 22nd century, a paraplegic Marine is di..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,"Captain Barbossa, long believed to be dead, ha..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,A cryptic message from Bond’s past sends him o...
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,Following the death of District Attorney Harve...
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,"John Carter is a war-weary, former military ca..."

In [ ]:
new_df = df[['id','title','tags']]

print("------------------- columns ---------------------")
print(new_df.columns)

print("------------------- info ---------------------")
print(new_df.info())

------------------- columns ---------------------
Index(['id', 'title', 'tags'], dtype='object')
------------------- info ---------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4803 non-null   int64
 1   title   4803 non-null   object
 2   tags    4800 non-null   object
dtypes: int64(1), object(2)
memory usage: 112.7+ KB
None

In [ ]:
print(new_df.head())

       id                                     title  \
0   19995                                    Avatar
1     285  Pirates of the Caribbean: At World's End
2  206647                                   Spectre
3   49026                     The Dark Knight Rises
4   49529                               John Carter

                                                tags
0  In the 22nd century, a paraplegic Marine is di...
1  Captain Barbossa, long believed to be dead, ha...
2  A cryptic message from Bond’s past sends him o...
3  Following the death of District Attorney Harve...
4  John Carter is a war-weary, former military ca...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv = CountVectorizer(max_features = 10000, stop_words = 'english')
cv

CountVectorizer(max_features=10000, stop_words='english')

In [ ]:
vec = cv.fit_transform(df['tags'].values.astype('U')).toarray()
vec

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4803, 10000))

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
sim = cosine_similarity(vec)
sim

array([[1.        , 0.5547002 , 0.41561947, ..., 0.31300428, 0.        ,
        0.09656091],
       [0.5547002 , 1.        , 0.40585385, ..., 0.30564977, 0.        ,
        0.08703883],
       [0.41561947, 0.40585385, 1.        , ..., 0.25764051, 0.        ,
        0.0733674 ],
       ...,
       [0.31300428, 0.30564977, 0.25764051, ..., 1.        , 0.05463584,
        0.09208868],
       [0.        , 0.        , 0.        , ..., 0.05463584, 1.        ,
        0.04494666],
       [0.09656091, 0.08703883, 0.0733674 , ..., 0.09208868, 0.04494666,
        1.        ]], shape=(4803, 4803))

In [ ]:
dist = sorted(list(enumerate(sim[0])), reverse = True, key= lambda vec : vec[1])

In [ ]:
dist

[(0, np.float64(1.0)),
 (4401, np.float64(0.6805446536716203)),
 (1191, np.float64(0.6793662204867574)),
 (322, np.float64(0.6702627371054852)),
 (4344, np.float64(0.6614769048245085)),
 (931, np.float64(0.6504436355879908)),
 (1652, np.float64(0.6502503675297687)),
 (2069, np.float64(0.6408069008390094)),
 (2163, np.float64(0.6361464251628642)),
 (1518, np.float64(0.6355715852811654)),
 (232, np.float64(0.6329621044272917)),
 (151, np.float64(0.6289709020331511)),
 (539, np.float64(0.6278279410632249)),
 (61, np.float64(0.6251954041004443)),
 (1825, np.float64(0.6245226097015943)),
 (2995, np.float64(0.6210344279375828)),
 (922, np.float64(0.6204965959947126)),
 (1277, np.float64(0.6204965959947126)),
 (495, np.float64(0.6163335513613657)),
 (72, np.float64(0.6150752708765851)),
 (972, np.float64(0.6150752708765851)),
 (1155, np.float64(0.6114295984380816)),
 (1198, np.float64(0.6072843866271672)),
 (920, np.float64(0.6064457948612227)),
 (505, np.float64(0.6054728454665549)),
 (4670, np.float64(0.6054728454665549)),
 (1044, np.float64(0.6054055145966812)),
 (31, np.float64(0.6052275326688024)),
 (46, np.float64(0.6035056869815845)),
 (4004, np.float64(0.6009252125773317)),
 (1827, np.float64(0.5995560487738422)),
 (33, np.float64(0.5974529834860508)),
 (122, np.float64(0.5974529834860508)),
 (1583, np.float64(0.5974529834860508)),
 (68, np.float64(0.5947010334500527)),
 (1192, np.float64(0.5907947710825321)),
 (490, np.float64(0.5897435897435898)),
 (2317, np.float64(0.5897435897435898)),
 (3350, np.float64(0.5897435897435898)),
 (977, np.float64(0.5883484054145521)),
 (1482, np.float64(0.5871365639519861)),
 (1438, np.float64(0.5855168737932974)),
 (850, np.float64(0.5853694070049636)),
 (2264, np.float64(0.5850532815798423)),
 (942, np.float64(0.5850098009747078)),
 (14, np.float64(0.5839272948338146)),
 (168, np.float64(0.583545480944036)),
 (123, np.float64(0.5823251360731083)),
 (1626, np.float64(0.580989067412121)),
 (654, np.float64(0.5765566601970551)),
 (618, np.float64(0.575982138666744)),
 (483, np.float64(0.5751973085430508)),
 (1936, np.float64(0.5751797717724086)),
 (2681, np.float64(0.5750080677718349)),
 (773, np.float64(0.5740646576733107)),
 (3993, np.float64(0.5740646576733107)),
 (581, np.float64(0.5728918992315463)),
 (935, np.float64(0.5728918992315463)),
 (196, np.float64(0.5718862635895968)),
 (1139, np.float64(0.5718776312789587)),
 (1271, np.float64(0.5718776312789587)),
 (627, np.float64(0.5714767668127443)),
 (859, np.float64(0.5698130754607257)),
 (2851, np.float64(0.5683985600588051)),
 (166, np.float64(0.5682911427735109)),
 (1750, np.float64(0.5682911427735109)),
 (200, np.float64(0.5676134788000512)),
 (1667, np.float64(0.5661385170722978)),
 (4267, np.float64(0.5661385170722978)),
 (233, np.float64(0.56496598177755)),
 (292, np.float64(0.5641025641025641)),
 (1296, np.float64(0.5631333371009477)),
 (96, np.float64(0.5628665689538624)),
 (1390, np.float64(0.5622474845923752)),
 (267, np.float64(0.560570203040462)),
 (813, np.float64(0.5605606616635938)),
 (1495, np.float64(0.560448538317805)),
 (1715, np.float64(0.560448538317805)),
 (1658, np.float64(0.5590852462516898)),
 (2157, np.float64(0.558156305651438)),
 (808, np.float64(0.5574946733380606)),
 (1136, np.float64(0.5574946733380606)),
 (1273, np.float64(0.5574946733380606)),
 (466, np.float64(0.5574946733380605)),
 (138, np.float64(0.5570066518960166)),
 (1341, np.float64(0.5563486402641868)),
 (370, np.float64(0.5561206856092701)),
 (1230, np.float64(0.5550302767044407)),
 (1, np.float64(0.5547001962252291)),
 (12, np.float64(0.5547001962252291)),
 (487, np.float64(0.5547001962252291)),
 (604, np.float64(0.5547001962252291)),
 (800, np.float64(0.5547001962252291)),
 (3352, np.float64(0.5547001962252291)),
 (1468, np.float64(0.5528230328172892)),
 (1569, np.float64(0.5528230328172892)),
 (2578, np.float64(0.5528230328172892)),
 (4724, np.float64(0.5528230328172892)),
 (784, np.float64(0.5501719556083908)),
 (2262, np.float64(0.5498823377682296)),
 (3494, np.float64(0.5498823377682296)),
 (2442, np.float64(0.5493612827995783)),
 (172, np.float64(0.5492350363810896)),
 (1320, np.float64(0.5492350363810896)),
 (3370, np.float64(0.5492350363810896)),
 (1617, np.float64(0.5490799884779068)),
 (28, np.float64(0.5490214034302319)),
 (152, np.float64(0.549010813046013)),
 (660, np.float64(0.549010813046013)),
 (1034, np.float64(0.549010813046013)),
 (2169, np.float64(0.549010813046013)),
 (112, np.float64(0.5477574921327173)),
 (1175, np.float64(0.547267233169888)),
 (35, np.float64(0.5464374431158983)),
 (94, np.float64(0.5464374431158983)),
 (511, np.float64(0.5464374431158983)),
 (1106, np.float64(0.5455005501394377)),
 (4734, np.float64(0.5455005501394377)),
 (10, np.float64(0.5447670420505112)),
 (4251, np.float64(0.5447670420505112)),
 (2375, np.float64(0.5444357229372963)),
 (4638, np.float64(0.5437149461664321)),
 (275, np.float64(0.5435828322181409)),
 (1068, np.float64(0.5435828322181409)),
 (4349, np.float64(0.5435828322181409)),
 (88, np.float64(0.5434929763894059)),
 (1024, np.float64(0.5434929763894059)),
 (410, np.float64(0.5416138323063244)),
 (594, np.float64(0.5413319619607667)),
 (1073, np.float64(0.5413319619607667)),
 (1331, np.float64(0.5413319619607667)),
 (1615, np.float64(0.5413319619607667)),
 (187, np.float64(0.540432519092169)),
 (4487, np.float64(0.539791896359413)),
 (2127, np.float64(0.5397606031684908)),
 (56, np.float64(0.537831591218683)),
 (260, np.float64(0.537831591218683)),
 (1538, np.float64(0.5372249195560548)),
 (4077, np.float64(0.5372131112471095)),
 (2346, np.float64(0.5371517298116736)),
 (4049, np.float64(0.536210189684388)),
 (899, np.float64(0.5349506156386411)),
 (1029, np.float64(0.5349506156386411)),
 (3372, np.float64(0.5349506156386411)),
 (121, np.float64(0.5330600392680743)),
 (744, np.float64(0.5329387100211931)),
 (2736, np.float64(0.5329387100211931)),
 (4465, np.float64(0.5329387100211931)),
 (70, np.float64(0.5321811563901743)),
 (349, np.float64(0.531688167718925)),
 (1001, np.float64(0.531587688049178)),
 (1110, np.float64(0.531587688049178)),
 (3177, np.float64(0.5310850045437943)),
 (2628, np.float64(0.5296199396711576)),
 (2845, np.float64(0.5296199396711576)),
 (711, np.float64(0.5278870442575004)),
 (1201, np.float64(0.5278870442575004)),
 (1294, np.float64(0.5278870442575004)),
 (2556, np.float64(0.5278870442575004)),
 (1144, np.float64(0.5264981264926564)),
 (3617, np.float64(0.5264981264926564)),
 (4565, np.float64(0.5264981264926564)),
 (208, np.float64(0.5262348115842175)),
 (330, np.float64(0.5262348115842175)),
 (2781, np.float64(0.5262348115842175)),
 (1083, np.float64(0.5261353625024291)),
 (1093, np.float64(0.5261353625024291)),
 (358, np.float64(0.5251641394443731)),
 (2084, np.float64(0.5251641394443731)),
 (2678, np.float64(0.5251641394443731)),
 (4563, np.float64(0.5251641394443731)),
 (100, np.float64(0.5251509076289175)),
 (1731, np.float64(0.5251509076289175)),
 (2826, np.float64(0.5242965552319168)),
 (3630, np.float64(0.5241424183609591)),
 (3568, np.float64(0.5238835186571609)),
 (2860, np.float64(0.5229763603684907)),
 (870, np.float64(0.5211727490313541)),
 (305, np.float64(0.5204834387696162)),
 (732, np.float64(0.5204834387696162)),
 (104, np.float64(0.5195243334661311)),
 (205, np.float64(0.5195243334661311)),
 (2474, np.float64(0.5195243334661311)),
 (941, np.float64(0.5194113811148742)),
 (3618, np.float64(0.5194113811148742)),
 (4539, np.float64(0.5194113811148742)),
 (82, np.float64(0.5188745216627708)),
 (1531, np.float64(0.5182002205050367)),
 (167, np.float64(0.5182002205050366)),
 (534, np.float64(0.5176775776887458)),
 (2490, np.float64(0.5176775776887457)),
 (149, np.float64(0.5168113941217019)),
 (754, np.float64(0.5168113941217019)),
 (131, np.float64(0.5167523265868931)),
 (1303, np.float64(0.5157158087305063)),
 (134, np.float64(0.514443402768482)),
 (2155, np.float64(0.514443402768482)),
 (2320, np.float64(0.514443402768482)),
 (2639, np.float64(0.514443402768482)),
 (1695, np.float64(0.5143028508594514)),
 (577, np.float64(0.5142653638627284)),
 (3323, np.float64(0.5142653638627284)),
 (459, np.float64(0.5138560194537569)),
 (26, np.float64(0.5128205128205128)),
 (117, np.float64(0.5128205128205128)),
 (174, np.float64(0.5128205128205128)),
 (1134, np.float64(0.5128205128205128)),
 (2515, np.float64(0.5128205128205128)),
 (2757, np.float64(0.5128205128205128)),
 (1625, np.float64(0.5128056050307795)),
 (985, np.float64(0.5124707431905382)),
 (3002, np.float64(0.5124100921762789)),
 (4499, np.float64(0.5124100921762789)),
 (2156, np.float64(0.5109523080212683)),
 (2590, np.float64(0.5095246653650681)),
 (1101, np.float64(0.509524665365068)),
 (1515, np.float64(0.509524665365068)),
 (2333, np.float64(0.509524665365068)),
 (2655, np.float64(0.509524665365068)),
 (87, np.float64(0.5084751798731267)),
 (215, np.float64(0.5084751798731267)),
 (973, np.float64(0.5084751798731267)),
 (767, np.float64(0.5076664070057264)),
 (564, np.float64(0.5070724870494425)),
 (778, np.float64(0.506944777064531)),
 (2863, np.float64(0.506944777064531)),
 (1082, np.float64(0.5063696835418333)),
 (3523, np.float64(0.5063696835418333)),
 (76, np.float64(0.5058917507467712)),
 (249, np.float64(0.5054958784325447)),
 (1002, np.float64(0.5054958784325447)),
 (1402, np.float64(0.5054958784325447)),
 (3988, np.float64(0.5054958784325447)),
 (4160, np.float64(0.5054958784325447)),
 (4327, np.float64(0.5054958784325447)),
 (4399, np.float64(0.5054958784325447)),
 (312, np.float64(0.5048781642974014)),
 (243, np.float64(0.5048781642974013)),
 (472, np.float64(0.5048781642974013)),
 (403, np.float64(0.50444309564243)),
 (1757, np.float64(0.504356277224002)),
 (1266, np.float64(0.5032599119588452)),
 (2336, np.float64(0.5032599119588452)),
 (97, np.float64(0.5025920339587095)),
 (109, np.float64(0.5024594344170622)),
 (624, np.float64(0.5024594344170622)),
 (695, np.float64(0.5024594344170622)),
 (1318, np.float64(0.5024594344170622)),
 (1404, np.float64(0.5024594344170622)),
 (176, np.float64(0.5017452060042545)),
 (776, np.float64(0.5017452060042545)),
 (1470, np.float64(0.5017452060042545)),
 (2775, np.float64(0.5017452060042545)),
 (2784, np.float64(0.5017452060042545)),
 (3126, np.float64(0.5017452060042545)),
 (4513, np.float64(0.501280411827603)),
 (1914, np.float64(0.5011856786864703)),
 (203, np.float64(0.5011856786864702)),
 (271, np.float64(0.5011856786864702)),
 (4427, np.float64(0.5008354224706334)),
 (1932, np.float64(0.5007448238897286)),
 (1078, np.float64(0.5003258390700999)),
 (1878, np.float64(0.5003258390700999)),
 (400, np.float64(0.5001732201680236)),
 (1079, np.float64(0.5001732201680236)),
 (90, np.float64(0.5001563232803553)),
 (356, np.float64(0.5001563232803553)),
 (1076, np.float64(0.5001563232803553)),
 (4312, np.float64(0.5001563232803553)),
 (103, np.float64(0.4992301766027062)),
 (435, np.float64(0.4982018950236221)),
 (3051, np.float64(0.4969995442739832)),
 (278, np.float64(0.4966085446506601)),
 (334, np.float64(0.4966085446506601)),
 (587, np.float64(0.4966085446506601)),
 (1939, np.float64(0.49660854465066007)),
 (3833, np.float64(0.49660854465066)),
 (2327, np.float64(0.49653632643684836)),
 (371, np.float64(0.4959348919001854)),
 (2046, np.float64(0.4959348919001854)),
 (1465, np.float64(0.4958017728823799)),
 (98, np.float64(0.4943115327429807)),
 (715, np.float64(0.4943115327429807)),
 (1178, np.float64(0.4943115327429807)),
 (2388, np.float64(0.4943115327429807)),
 (2558, np.float64(0.4943115327429807)),
 (3073, np.float64(0.4943115327429807)),
 (3359, np.float64(0.4943115327429807)),
 (3722, np.float64(0.4943115327429807)),
 (4408, np.float64(0.4943115327429807)),
 (78, np.float64(0.4941662111074008)),
 (198, np.float64(0.4941662111074008)),
 (309, np.float64(0.4941662111074008)),
 (2573, np.float64(0.4941662111074008)),
 (1654, np.float64(0.49354811679282456)),
 (1938, np.float64(0.49354811679282456)),
 (4470, np.float64(0.49354811679282456)),
 (7, np.float64(0.49329338226396247)),
 (332, np.float64(0.49329338226396247)),
 (452, np.float64(0.4932933822639624)),
 (2291, np.float64(0.4932933822639624)),
 (3293, np.float64(0.4932933822639624)),
 (381, np.float64(0.49306684108909254)),
 (1721, np.float64(0.49306684108909254)),
 (3826, np.float64(0.49306684108909254)),
 (2509, np.float64(0.4930668410890925)),
 (238, np.float64(0.49223296033190167)),
 (300, np.float64(0.4921545663875499)),
 (2815, np.float64(0.4921545663875499)),
 (485, np.float64(0.4920554208628378)),
 (503, np.float64(0.4920554208628378)),
 (2967, np.float64(0.49065338146265824)),
 (543, np.float64(0.4906533814626582)),
 (782, np.float64(0.4906533814626582)),
 (510, np.float64(0.4904989276604043)),
 (3151, np.float64(0.4902903378454601)),
 (4715, np.float64(0.4902903378454601)),
 (768, np.float64(0.48953546389837893)),
 (665, np.float64(0.48919959047022854)),
 (774, np.float64(0.48919959047022854)),
 (3349, np.float64(0.48919959047022854)),
 (263, np.float64(0.4889177122615932)),
 (1259, np.float64(0.4889177122615932)),
 (1367, np.float64(0.4889177122615932)),
 (3715, np.float64(0.4889177122615932)),
 (50, np.float64(0.4885271508527602)),
 (241, np.float64(0.4885271508527602)),
 (91, np.float64(0.4883862905055044)),
 (339, np.float64(0.4883862905055043)),
 (4353, np.float64(0.4883862905055043)),
 (741, np.float64(0.48781831828142963)),
 (108, np.float64(0.4878183182814296)),
 (369, np.float64(0.4878183182814296)),
 (1610, np.float64(0.4871987657646901)),
 (4039, np.float64(0.4871987657646901)),
 (1052, np.float64(0.48719876576469)),
 (1694, np.float64(0.48719876576469)),
 (3332, np.float64(0.48719876576469)),
 (3416, np.float64(0.48719876576469)),
 (3940, np.float64(0.48719876576469)),
 (207, np.float64(0.48717948717948717)),
 (2372, np.float64(0.48717948717948717)),
 (116, np.float64(0.48545977336288587)),
 (276, np.float64(0.4841820261350419)),
 (781, np.float64(0.4841820261350419)),
 (3271, np.float64(0.4841820261350419)),
 (2250, np.float64(0.484140908388279)),
 (810, np.float64(0.483896457236042)),
 (1596, np.float64(0.483896457236042)),
 (950, np.float64(0.48347776099697937)),
 (3795, np.float64(0.4819291099718668)),
 (165, np.float64(0.48121773951145314)),
 (449, np.float64(0.48121773951145314)),
 (1286, np.float64(0.48121773951145314)),
 (2253, np.float64(0.48121773951145314)),
 (2966, np.float64(0.48121773951145314)),
 (3230, np.float64(0.48105119936474167)),
 (101, np.float64(0.4810511993647416)),
 (83, np.float64(0.4807401700618652)),
 (228, np.float64(0.4803844614152614)),
 (1379, np.float64(0.4803844614152614)),
 (2066, np.float64(0.4803844614152614)),
 (2108, np.float64(0.4803844614152614)),
 (36, np.float64(0.48038446141526137)),
 (3492, np.float64(0.48038446141526137)),
 (4460, np.float64(0.48038446141526137)),
 (976, np.float64(0.47947892910884576)),
 (1246, np.float64(0.4794789291088457)),
 (2055, np.float64(0.4779521193992432)),
 (3882, np.float64(0.4779521193992432)),
 (3724, np.float64(0.47756693294091923)),
 (2237, np.float64(0.47740991602628857)),
 (3148, np.float64(0.47740991602628857)),
 (537, np.float64(0.47576082676004205)),
 (4620, np.float64(0.47576082676004205)),
 (3920, np.float64(0.47555635434073024)),
 (2008, np.float64(0.4755563543407302)),
 (212, np.float64(0.4754664825919657)),
 (1213, np.float64(0.4754623596271881)),
 (52, np.float64(0.47514850711633755)),
 (242, np.float64(0.47514850711633755)),
 (4225, np.float64(0.47514850711633755)),
 (164, np.float64(0.47509288974080416)),
 (1361, np.float64(0.47509288974080416)),
 (3006, np.float64(0.47509288974080416)),
 (67, np.float64(0.4750168687962836)),
 (2972, np.float64(0.47501686879628346)),
 (1449, np.float64(0.4745614042601291)),
 (1074, np.float64(0.4738704723373514)),
 (2645, np.float64(0.4738704723373514)),
 (329, np.float64(0.47384831384339077)),
 (533, np.float64(0.47384831384339077)),
 (568, np.float64(0.47384831384339077)),
 (1206, np.float64(0.47384831384339077)),
 (1272, np.float64(0.47384831384339077)),
 (2568, np.float64(0.47384831384339077)),
 (2790, np.float64(0.47384831384339077)),
 (106, np.float64(0.473049916791266)),
 (195, np.float64(0.4721921646498856)),
 (840, np.float64(0.4721921646498856)),
 (1324, np.float64(0.4721921646498856)),
 (1507, np.float64(0.4721921646498856)),
 (1682, np.float64(0.4721921646498856)),
 (2114, np.float64(0.4721921646498856)),
 (777, np.float64(0.4710557197659958)),
 (2268, np.float64(0.4710557197659958)),
 (3068, np.float64(0.4710557197659958)),
 (335, np.float64(0.47087095579741867)),
 (794, np.float64(0.47087095579741867)),
 (412, np.float64(0.4695064218280435)),
 (86, np.float64(0.46950642182804336)),
 (254, np.float64(0.46950642182804336)),
 (350, np.float64(0.46950642182804336)),
 (16, np.float64(0.46945790055203074)),
 (236, np.float64(0.46945790055203074)),
 (45, np.float64(0.46894509514701554)),
 (27, np.float64(0.468539570493646)),
 (234, np.float64(0.468539570493646)),
 (336, np.float64(0.4677642769637489)),
 (547, np.float64(0.4677642769637489)),
 (1030, np.float64(0.4677642769637489)),
 (1707, np.float64(0.4677642769637489)),
 (461, np.float64(0.46757190011951805)),
 (546, np.float64(0.467571900119518)),
 (762, np.float64(0.467571900119518)),
 (1460, np.float64(0.467571900119518)),
 (1664, np.float64(0.467571900119518)),
 (2915, np.float64(0.467571900119518)),
 (3336, np.float64(0.467571900119518)),
 (3966, np.float64(0.467571900119518)),
 (653, np.float64(0.46744639430592455)),
 (1072, np.float64(0.46744639430592455)),
 (1978, np.float64(0.46744639430592455)),
 (2796, np.float64(0.46744639430592455)),
 (3591, np.float64(0.46744639430592455)),
 (199, np.float64(0.46714183586705177)),
 (294, np.float64(0.4671418358670517)),
 (2614, np.float64(0.4671418358670517)),
 (3035, np.float64(0.4671418358670517)),
 (319, np.float64(0.4668497809239262)),
 (476, np.float64(0.4668497809239262)),
 (1238, np.float64(0.4668497809239262)),
 (442, np.float64(0.4663213712685439)),
 (929, np.float64(0.4663213712685439)),
 (607, np.float64(0.4662106981042301)),
 (62, np.float64(0.46604138242837045)),
 (2577, np.float64(0.4654746681256314)),
 (111, np.float64(0.4639669759802292)),
 (333, np.float64(0.4639669759802291)),
 (683, np.float64(0.4626519455729921)),
 (1287, np.float64(0.4626519455729921)),
 (1836, np.float64(0.4626519455729921)),
 (1686, np.float64(0.46259244432580726)),
 (1976, np.float64(0.46256884688429795)),
 (2403, np.float64(0.46256884688429795)),
 (544, np.float64(0.4622501635210243)),
 (826, np.float64(0.4622501635210243)),
 (1193, np.float64(0.4622501635210243)),
 (2225, np.float64(0.4622501635210243)),
 (3799, np.float64(0.4622501635210243)),
 (634, np.float64(0.4622501635210242)),
 (1111, np.float64(0.4622501635210242)),
 (4069, np.float64(0.4622501635210242)),
 (4639, np.float64(0.4622501635210242)),
 (3361, np.float64(0.46190116372531287)),
 (2198, np.float64(0.46153846153846156)),
 (433, np.float64(0.4615384615384615)),
 (455, np.float64(0.4615384615384615)),
 (590, np.float64(0.4615384615384615)),
 (621, np.float64(0.4615384615384615)),
 (858, np.float64(0.4615384615384615)),
 (1049, np.float64(0.4615384615384615)),
 (2835, np.float64(0.4615384615384615)),
 (3671, np.float64(0.4615384615384615)),
 (216, np.float64(0.46015784683444066)),
 (290, np.float64(0.46015784683444066)),
 (314, np.float64(0.46015784683444066)),
 (801, np.float64(0.46015784683444066)),
 (1095, np.float64(0.46015784683444066)),
 (148, np.float64(0.46013216766665177)),
 (220, np.float64(0.46013216766665177)),
 (362, np.float64(0.46013216766665177)),
 (1070, np.float64(0.46013216766665177)),
 (1344, np.float64(0.46013216766665177)),
 (2047, np.float64(0.46013216766665177)),
 (2389, np.float64(0.46013216766665177)),
 (3351, np.float64(0.46013216766665177)),
 (184, np.float64(0.45976310619833144)),
 (325, np.float64(0.4586643221060042)),
 (4286, np.float64(0.4586643221060042)),
 (807, np.float64(0.45863201914759155)),
 (160, np.float64(0.45802861241434445)),
 (1269, np.float64(0.45760431532242946)),

In [ ]:
len(dist)

4803

In [ ]:
for i in dist[0:5]:
    print(new_df.iloc[i[0]].title)

Avatar
The Helix... Loaded
Small Soldiers
The Fifth Element
Godzilla 2000

In [ ]:
def recommend(movie):
    # get id of movie
    idx = new_df[new_df['title']== movie].index[0]

    dist = sorted(list(enumerate(sim[idx])), reverse = True, key= lambda vec : vec[1])

    for i in dist[0:5]:
        print(new_df.iloc[i[0]].title)

In [ ]:
recommend('Avatar')

Avatar
The Helix... Loaded
Small Soldiers
The Fifth Element
Godzilla 2000

In [ ]:
recommend('Godzilla 2000')

Godzilla 2000
The Helix... Loaded
The Covenant
Dragon Wars: D-War
Small Soldiers

In [ ]:
recommend('The Fifth Element')

The Fifth Element
Race to Witch Mountain
Dragonball Evolution
The Covenant
The Helix... Loaded

In [ ]:
recommend('Iron Man')

Iron Man
The Helix... Loaded
Godzilla 2000
Iron Man 3
Mad Max